version: '3.7'
services:
  #===================================================
  # SERVER BACKEND
  #===================================================
  backend:
    build:
      context: backend
      dockerfile: dockerfile
    container_name: app
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
    - 8085:8085
    networks:
      - dev-network
  #===================================================
  # SERVER FRONTEND - NGINX
  #===================================================
  front:
    build: 
      context: frontend
      dockerfile: dockerfile
    container_name: nginx
    #volumes:
    #  - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - dev-network
  #===================================================
  # SERVER MARIADB
  #===================================================
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234567
      MARIADB_ROOT_PASSWORD: 1234567
    ports:
      - 3307:3306
    volumes:
      - ./.data/mariadb/data:/var/lib/mariadb
    networks:
      - dev-network
  #===================================================
  # SERVER PHPMYADMIN
  #===================================================

#===================================================
# NETWORK
#===================================================
networks:
  dev-network:
    driver: bridge